// Generated by https://quicktype.io

export interface UserInterface {
    data:    UserInfoInterface;
}

export interface UserInfoInterface {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
}
